language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t arthurburle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arthurburle/react-test npm test -- --coverage

after_success:
  - docker build -t arthurburle/multi-client ./client
  - docker build -t arthurburle/multi-nginx ./nginx
  - docker build -t arthurburle/multi-server ./server
  - docker build -t arthurburle/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arthurburle/multi-client
  - docker push arthurburle/multi-nginx
  - docker push arthurburle/multi-server
  - docker push arthurburle/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-sa-east-1-175515831517
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
